/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Get the absolute value based on the provided base value and percentage */
#define GET_ABS_FROM_PERCENT(val,percent) ((val) * (percent) / 100)

/* The initial trigger position in percent of the PWM period */
#define INITIAL_TRIGGER_POS_PERCENT       ((arduinoTcpwmD6_config.compare2 * 100ul) / arduinoTcpwmD6_config.period0)

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void initArduinoTcpwmD6(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;
    uint8_t uartReadValue;
    uint8_t triggerPosPercent;

#if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdt_obj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    result = cyhal_wdt_init(&wdt_obj, cyhal_wdt_get_max_timeout_ms());
    CY_ASSERT(CY_RSLT_SUCCESS == result);
    cyhal_wdt_free(&wdt_obj);
#endif /* #if defined (CY_DEVICE_SECURE) */

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    
    /* Board init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE);

    /* retarget-io init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");
    printf("****************** Trigger Multiplexer TRIG_DBG Code Example ******************\r\n");

    /* Initialize and start TCPWM */
    initArduinoTcpwmD6();

    triggerPosPercent = INITIAL_TRIGGER_POS_PERCENT;
 
    printf("Observe the PWM signal and the TRIG_DBG signal on the scope.\r\n\r\n");
    printf("Press '+' key to move the TCPWM trigger to a later point in the PWM period\r\n");
    printf("Press '-' key to move the TCPWM trigger to an earlier point in the PWM period\r\n\r\n");

    printf("Current trigger position: %3u %%\r\n", triggerPosPercent);

    for (;;)
    {
        /* Check if '+' or '-' key was pressed */
        if (cyhal_uart_getc(&cy_retarget_io_uart_obj, &uartReadValue, 1) == CY_RSLT_SUCCESS)
        {
            if ((uartReadValue == '-') || (uartReadValue == '+'))
            {
                /* Check for limits and increment/decrement accordingly */
                if ((uartReadValue == '-') && (triggerPosPercent > 0))
                {
                    triggerPosPercent--;
                }
                else if ((uartReadValue == '+') && (triggerPosPercent < 100))
                {
                    triggerPosPercent++;
                }

                /* Convert the percent value into the appropriate number of ticks because the API expects ticks */
                uint32_t compareTicks = GET_ABS_FROM_PERCENT(arduinoTcpwmD6_config.period0, triggerPosPercent);

                /* Apply the new trigger position */
                Cy_TCPWM_PWM_SetCompare1Val(arduinoTcpwmD6_HW, arduinoTcpwmD6_NUM, compareTicks);

                /* Move cursor to previous line and update the value for the trigger position */
                printf("\x1b[1F");
                printf("Current trigger position: %3u %%\r\n", triggerPosPercent);
            }
        }
    }
}

/**********************************************************************************************************************
 * Function Name: initArduinoTcpwmD6
 * Summary:
 *  Initializes, enables and starts the TCPWM instance that is routed to the
 *  Arduino D6 pin. Refer Device Configurator or generated source code for actual settings.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
void initArduinoTcpwmD6(void)
{
    cy_en_tcpwm_status_t tcpwmStatus;

    tcpwmStatus = Cy_TCPWM_PWM_Init(arduinoTcpwmD6_HW, arduinoTcpwmD6_NUM, &arduinoTcpwmD6_config);
    if (tcpwmStatus != CY_TCPWM_SUCCESS)
    {
        CY_ASSERT(0);
    }

    Cy_TCPWM_PWM_Enable(arduinoTcpwmD6_HW, arduinoTcpwmD6_NUM);
    Cy_TCPWM_TriggerStart_Single(arduinoTcpwmD6_HW, arduinoTcpwmD6_NUM);
}

/* [] END OF FILE */
